after-login-command = [
  'exec-and-forget open -n /Applications/Nix\ Apps/Signal.app --args --use-tray-icon',
]
after-startup-command = [
  "exec-and-forget osascript -e 'quit app \"AutoRaise\"'",
  "exec-and-forget open -n /Applications/AutoRaise.app --args -pollMillis 50 -delay 1 -scale 2.5 -altTaskSwitcher false -ignoreSpaceChanged false -disableKey control -mouseDelta 100.0",
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

# [gaps]
# inner.horizontal = 10
# inner.vertical = 10
# outer.left = 10
# outer.bottom = 10
# outer.top = 10
# outer.right = 10

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'


alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'


alt-shift-c = 'close --quit-if-last-window'
alt-shift-enter = 'exec-and-forget open -n /Applications/Nix\ Apps/Kitty.app'
alt-shift-f = 'exec-and-forget open -n /Applications/Nix\ Apps/LibreWolf.app'
alt-shift-s = 'exec-and-forget open -n /Applications/Nix\ Apps/Signal.app --args --use-tray-icon'
alt-shift-p = "exec-and-forget karabiner_cli --select-profile 'Krita'"
alt-shift-o = "exec-and-forget karabiner_cli --select-profile 'Rebelle'"
alt-shift-a = "exec-and-forget osascript -e 'quit app \"AutoRaise\"' && open -n /Applications/AutoRaise.app --args -pollMillis 50 -delay 1 -scale 2.5 -altTaskSwitcher false -ignoreSpaceChanged false -disableKey control -mouseDelta 100.0"

alt-shift-semicolon = 'mode service'

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = ['layout floating']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
# autoraise reset
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
